### ISSUE TITLE
Testing needs mask and pose imformation along with model image and target cloth?

### ISSUE THREAD

**Issue by hamaadtahiir** [benquick123/C-VTON#1]
I have done the testing with pretrained model on vton dataset. It looks to me that the testing needs all the other information along with model, cloth and edge, such as densepose, masks etc. Shouldnt testing only need model image, cloth and its edge?

**Comment by benquick123** [comment]
I see why there might be some confusion. The dataset that loads the data are the same no matter if it is used for training or testing. However, while you will have to tweak the VitonDataset.py and MPVDataset.py to *not* load additional assets during testing, only the images you mentioned are used in the testing phase.

**Comment by hamaadtahiir** [comment]
so it means that the segmentation information is required in the testing phase
