### ISSUE TITLE
How can try to dress the person in the photo?

### ISSUE THREAD

**Issue by goodwin74** [benquick123/C-VTON#10]
Is it possible to take my photo of clothes and my photo of a person and combine them? Or is it only possible to see test data here?

**Comment by maizer2** [comment]
If you want to dress-up using your data like this paper, you need to training for your dataset. but it's not easy way.

**Comment by goodwin74** [comment]
> If you want to dress-up using your data like this paper, you need to training for your dataset. but it's not easy way.

Just wondering what is the profit if in order to put clothes on a person, you need to train a model, with data where there will be clothes and there will be a person ?!
It’s easier then to take clothes and take a picture of a person and publish it. Because for training you still have to wear clothes to teach the model and it will take a lot of photos.
Therefore, I thought C-VTON has an already trained model, which allows you to make a person in these clothes from a photo of clothes and a photo of a person without any problems. Otherwise, what is the point of all this?!

**Comment by ajdal** [comment]
C-VTON does indeed come with models trained on VITON and MPV datasets, so in theory you can run it on your own data if you follow the preprocessing steps described in the paper. However, if the data differs significantly from the data that was used for training and testing the models, or you use different models for preprocessing, we can not guarantee that the quality of the results will match the quality reported in the paper.
