### ISSUE TITLE
How to achieve FID like experiment in paper

### ISSUE THREAD

**Issue by zero-nnkn** [benquick123/C-VTON#14]
Hi, 
I try to evaluate FID on the cleaned VITON dataset (416 images) with [the generated test results](https://unilj-my.sharepoint.com/:u:/g/personal/ajda_lampe_fri1_uni-lj_si/EUGuq5g2GsVMhr8-SJaJzOsBAv3eV2u5lYHNaVs48jg5rQ?e=rM89CX) that this repo provides.
I use [pytorch-fid](https://github.com/mseitzer/pytorch-fid/tree/master/src/pytorch_fid) to calculate FID. However, the result is worse than reported in the paper (37.05 and 19.54). Maybe my method is wrong, could you tell me how to reproduce the fid results?

<img width="703" alt="image" src="https://github.com/benquick123/C-VTON/assets/60695920/d9c64344-c203-4677-a485-78f71d6d2458">

**Comment by benquick123** [comment]
Hi, that is interesting. Unfortunately, I do not remember the exact details of the testing regime, but I would assume that for our work the code found in the folder [utils](https://github.com/benquick123/C-VTON/tree/main/utils) was used. I will have to let you figure the rest out yourself.
