### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nebojsa-bozanic** [benquick123/C-VTON#3]
Hey folks,

Thanks for the great work! 

Would you mind updating the license file?

Cheers,
Nebojsa

**Comment by benquick123** [comment]
The licence has been updated, thank you for your inquiry.

**Comment by nebojsa-bozanic** [comment]
That's great! Thanks!

A follow-up question: Are you open to using an MIT or BSD-2-Clause License for your repo? it would enable more folks to be able to work on it and possibly contribute as well.

Cheers!

**Comment by benquick123** [comment]
The guiding reasons behind the choice of this particular licence were (i) open source, (ii) free for non-commercial use and (iii) author attribution when using the code (either by referencing the paper or this repository). If you can confirm that the two licences you are suggesting conform to these criteria, we would consider changing it.

Thanks for your suggestions in any case.
