### ISSUE TITLE
no person images and clothing images

### ISSUE THREAD

**Issue by maguro27** [benquick123/C-VTON#4]
Hi.
Although I tried to run the test script, the script throws errors in `./dataloader/MPVDataset.py`.
There are no person images and clothing images in `./data/mpv/xxxxxx`.
For instance, the clothing image does not exist when desired clothing path is `./data/mpv/BJ721D039/BJ721D039-Q11@12=cloth_front.jpg`.
Please teach me how to solve this problem.
Thanks.

**Comment by benquick123** [comment]
That is indeed the case, since we are not allowed to share the dataset due to copyright issues. I am sure you will find some version of the data we used on the internet.
