### ISSUE TITLE
About VITON-HD

### ISSUE THREAD

**Issue by omihub777** [benquick123/C-VTON#6]
Hi,

Thank you for your great work! I want to clarify what VITON-HD refers to in your project. My understanding is that VITON-HD is a full resolution version of the original [VITON](https://openaccess.thecvf.com/content_cvpr_2018/html/Han_VITON_An_Image-Based_CVPR_2018_paper.html), which you get from the authors of [the work](https://openaccess.thecvf.com/content_cvpr_2018/html/Han_VITON_An_Image-Based_CVPR_2018_paper.html) directly. Is my understanding correct?
My confusion comes from the fact there is a dataset (more like a model?) called [VITON-HD](https://github.com/shadow2496/VITON-HD). I thought VITON-HD in your project refers to this [VITON-HD](https://github.com/shadow2496/VITON-HD) but it seems not.

I really appreciate your help.

**Comment by benquick123** [comment]
Hi, I agree there is some confusion about the naming scheme. In our paper, we used the VITON dataset, except we obtained it in high resolution, which we call (similarly to some other papers) VITON-HD.

However, as you mention, the paper introducing VITON-HD \***model*** also exists, but you should check whether its authors also used the same dataset as we did or not.
