### ISSUE TITLE
FID evaluation

### ISSUE THREAD

**Issue by JacksonCakes** [benquick123/C-VTON#7]
Hi, thank you for your great work! May I know why the FID score presented on your paper (Table 1) is so much different from the one reported in their original paper? For example, the FID score reported for PF-AFN is 10.09 on VTON dataset while it's reported as 27.23 in your paper.

**Comment by benquick123** [comment]
Hi, as we mention in the paper, VITON dataset consists of duplicate images found in training and test sets. After their removal both the content and size of the test set changed, affecting the FID scores in return. Note that we made special effort in changing the test set only, while keeping the train set the same in an aim to ensure fair comparison between all state-of-the-art approaches.
